### PR TITLE
Make distro list expandable on snap details page

### LINKED ISSUE #2000: List of distributions the snap package installed on is so long.
### Expected behaviour
In the lower portion where we are listing the distributions where the snap has been installed by users (metrics) is so long for some snaps which is not browser friendly (specially on mobile) users have to keep scrolling to reach bottom.

### Steps to reproduce the problem
Visit the page for spotify app https://snapcraft.io/spotify

### Specs

- _URL:_  https://snapcraft.io/spotify
- _Operating system:_ Android O (or any)
- _Browser:_ Chrome (latest) or any browser.

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Make distro list expandable on `snap details` page

## Issue / Card

Fixes #2000 

## QA

- Pull the branch
- Run the site using the command `./run`
- View the site locally in your web browser at: http://0.0.0.0:8004/spotify or any other snap
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Scroll down to the distro list and click the `Show more` button
- See the list is expanded
- For design check compare to [this comment](https://github.com/canonical-web-and-design/snapcraft.io/issues/2000#event-2950599628)

### CODE REVIEW

**Comment by Lukewh** [comment]
Could we add a "Show less" when it's open too?
Also on snaps with few users:
Screenshot_2020-01-15 Install boop-friday for Linux using the Snap Store Snapcraft

**Comment by Lukewh** [comment]
Also doesn't really work on mobile for short lists:
Screen Shot 2020-01-15 at 16 23 31

**Comment by Lukewh** [comment]
Screen Shot 2020-01-16 at 13 58 41
Not seeing the show/hide links on mobile - or is that not what @danielmutis meant?

File: static/js/public/snap-details/exapandable-distr-chart.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
+export default function initExpandableDistroChart() {
+  const moreEl = document.querySelector(".snapcraft-distro-chart__more");
+  const lessEl = document.querySelector(".snapcraft-distro-chart__less");
+  const detailsEl = document.querySelector(".snapcraft-distro-chart");
+
+  if (moreEl && lessEl && detailsEl && screen.width <= 772) {
```
Comment (Lukewh) [inline static/js/public/snap-details/exapandable-distr-chart.js]: We could probably add the `u-hide` and `u-show` classes in the markup to hide/show the buttons on desktop and mobile and remove the `screen.width` conditional. That way if someone reduces their screen size and the buttons show, they will still work.
Currently, if you reduce the size of the page the list of distros just gets cut off and if you increase the size of the page, the buttons remain.

File: static/js/public/snap-details/exapandable-distr-chart.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+    moreEl.classList.remove("u-hide");
```
Comment (Lukewh) [inline static/js/public/snap-details/exapandable-distr-chart.js]: Doing the above would mean we don't need to fiddle with hiding and showing via js.

File: templates/store/snap-details.html [hunk 3]
```diff
@@ -197,17 +197,17 @@ <h4>Share this snap</h4>
       </div>
 
       <div class="p-strip is-shallow">
-        <div class="row {% if normalized_os %}u-equal-height{% endif %}">
+        <div class="row {% if normalized_os %}u-equal-height{% endif %}" id="js-chart-row">
```
Comment (Lukewh) [inline templates/store/snap-details.html]: Where possible for JS hooks we should try and use the `data-js` attribute rather than id's and classes.
Then in the code you can do `document.querySelector("[data-js='chart-row']")`

File: templates/store/snap-details.html [hunk 4]
```diff
@@ -222,6 +222,14 @@ <h4>Users by distribution (log)</h4>
                   {% endfor %}
                 </div>
               </div>
+              {% if normalized_os|length > 10 %}
+              <div class="snapcraft-distro-chart__more u-hide">
+                <a href="/{{ package_name }}" class="js-show-more-description">Show more</a>
```
Comment (Lukewh) [inline templates/store/snap-details.html]: Again for these two `data-js="show-more-description"` and `data-js="show-less-description"`

File: templates/store/snap-details.html (hunk 3 above)
Comment (solazio) [reply templates/store/snap-details.html]: totally agree with that. Actually I forgot to remove this id, because is not used anywhere. Just used it to test something and then forgot to remove it.

**Comment by keshavbhatt** [comment]
:+1: :heart_eyes_cat:
