### PR TITLE
Fix spinner to show in FF

### LINKED ISSUE #2659: Spinner is not visible when disconnecting repo in Firefox
image

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Fix spinner to show in FF

## Issue / Card

Fixes #2659 

## QA

- Pull the branch
- Run the site using the command `./run`
- View the site locally in your web browser at: http://0.0.0.0:8004/<snap_name>/builds
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- **Use Firefox please!!!**
- Make sure the snap you look at has a GitHub repo connected. Click on `Disconnect repo` and then click `Confirm`
- You should see the button being disabled and a spinner should be visible, after that you should be redirected and you snap is disconnected from your repo

### CODE REVIEW

**Comment by solazio** [comment]
I added a 400ms timeout now, hopefully will work. If not I don't really know what else to do because for me all the fixes were working locally.
Screencast-2020-04-22-194452

File: static/js/publisher/builds/repoDisconnect.js [hunk 1]
```diff
@@ -32,11 +38,11 @@ function initRepoDisconnect() {
       });
     });
 
-    repoDisconnectConfirm.addEventListener("click", e => {
-      e.preventDefault();
+    repoDisconnectConfirm.addEventListener("click", () => {
+      setTimeout(() => {
```
Comment (Lukewh) [inline static/js/publisher/builds/repoDisconnect.js:42]: Adding a setTimeout pulls this outside of the main context - so when the page starts loading and the main context is suspended, this will still trigger.
