### PR TITLE
2746 create trigger new build component

### LINKED ISSUE #2746: Create new Trigger new build component
Include it in the "Builds" component.

- [ ] Onclick - POST to the trigger new build endpoint
- [ ] Onclick - Update state to "[loader] Requesting"
- [ ] When the first built result comes back from the builds component update to "Trigger new build"
- [ ] On error - display a generic "Something went wrong, please try again" notification above the table

### PR DESCRIPTION
**Pull request by solazio**
## Done

- `Trigger new build` on the frontend

## Issue / Card

Fixes #2746

## QA

- Pull the branch
- Run the site using the command `./run`
- View the site locally in your web browser at: http://0.0.0.0:8004/<snap_name>/builds
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Click the `Trigger new build` button and see the button is disable with a spinner until the table is reloaded

### CODE REVIEW

File: static/js/publisher/builds/index.js [hunk 1]
```diff
@@ -84,6 +101,30 @@ class Builds extends React.Component {
...
+      }
+    })
+      .then(res => res.json())
+      .then(result => {
+        if (result.success) {
+          this.setState({ triggerBuildSucccess: true });
+        }
+      })
+      .catch(() => {
+        this.setState({ triggerBuildSucccess: "ERROR" });
```
Comment (Lukewh) [inline static/js/publisher/builds/index.js:124]: we should define some consts for different states
```
const ERROR = "ERROR";
const SUCCESS = "SUCCESS";
const IDLE = "IDLE"
```

And use those, rather than a mix of boolean, string and null types.

File: static/js/publisher/builds/index.js [hunk 2]
```diff
@@ -84,6 +101,30 @@ class Builds extends React.Component {
...
+      headers: {
+        "Content-Type": "application/json",
+        "X-CSRFToken": csrf_token
+      }
+    })
+      .then(res => res.json())
+      .then(result => {
+        if (result.success) {
+          this.setState({ triggerBuildSucccess: true });
+        }
```
Comment (Lukewh) [inline static/js/publisher/builds/index.js:121]: There's also the `else` of `FORBIDDEN` that the API could return here.

File: static/js/publisher/builds/helpers.js [hunk 3]
```diff
@@ -80,3 +84,9 @@ export function createDuration(duration) {
   }
   return "";
 }
+
+export const TriggerBuildStatus = {
```
Comment (Lukewh) [inline static/js/publisher/builds/helpers.js:88]:
```suggestion
export const TriggerBuildStatus = {
  ERROR,
  SUCCESS,
  IDLE
};
```

File: static/js/publisher/builds/index.js [hunk 4]
```diff
@@ -62,13 +72,25 @@ class Builds extends React.Component {
...
       .then(res => res.json())
       .then(result => {
-        this.setState({
-          isLoading: false,
-          isTooSlow: builds.length === 0 && result.snap_builds.length === 0,
-          builds: fromStart
-            ? result.snap_builds
-            : builds.slice().concat(result.snap_builds)
-        });
+        if (triggerBuildSucccess === SUCCESS) {
```
Comment (Lukewh) [inline static/js/publisher/builds/index.js:75]: sorry I meant you don't need the if/else if you just make `triggerBuildLoading` and `triggerBuildSuccess` ternary operators. That way you don't need to repeat the `isLoading`, `isTooSlow` and `builds` keys - making it more complicated to update in the future.

File: static/js/publisher/builds/index.js [hunk 5]
```diff
@@ -15,6 +21,8 @@ class Builds extends React.Component {
     this.fetchTimer = null;
 
     this.state = {
+      triggerBuildLoading: false,
+      triggerBuildSucccess: false,
```
Comment (Lukewh) [inline static/js/publisher/builds/index.js:25]: as this can be `ERROR`, `SUCCESS` and `IDLE` now the initial state should probably be `IDLE` and the name of the variable would be better as `triggerBuildStatus`.

File: static/js/publisher/builds/index.js (hunk 4 above)
Comment (solazio) [reply static/js/publisher/builds/index.js:75]: ahhh, ok, sorry

File: static/js/publisher/builds/index.js [hunk 6]
```diff
@@ -63,6 +73,10 @@ class Builds extends React.Component {
       .then(res => res.json())
       .then(result => {
         this.setState({
+          triggerBuildLoading:
+            triggerBuildStatus === SUCCESS ? !SUCCESS : triggerBuildStatus,
+          triggerBuildStatus:
+            triggerBuildStatus === SUCCESS ? IDLE : triggerBuildStatus,
```
Comment (Lukewh) [inline static/js/publisher/builds/index.js:79]: I think the logic for these two needs clarifying - I get console errors. The first return of /builds.json marks it as done. On next fetch of /builds.json I get:
```
Warning: Failed prop type: Invalid prop `isLoading` of type `string` supplied to `TriggerBuild`, expected `boolean`.
    in TriggerBuild (created by Builds)
    in Builds react_devtools_backend.js:6:5119
```

Comment (solazio) [reply static/js/publisher/builds/index.js:79]: was supposed to use `triggerBuildLoading` instead on line 77
